import "./globals.css";

export const metadata = {
  title: "Frameworks",
  description: "Generated by create next app",
  applicationName: "Frameworks",
  keywords: "Frameworks",
  
  // Icons
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  
  // // Theme and Display
  // manifest: "/site.webmanifest",
  // themeColor: "#000000",
  // colorScheme: "dark light",
  
  // // Mobile Settings
  // viewport: {
  //   width: "device-width",
  //   initialScale: 1,
  //   maximumScale: 1,
  //   userScalable: "no",
  // },
  
  // // Progressive Web App
  // appleWebApp: {
  //   capable: true,
  //   title: "Frameworks",
  //   statusBarStyle: "default",
  // },
  // mobileWebApp: true,
  
  // // Author Info
  // authors: [
  //   {
  //     name: "Frameworks",
  //     url: "https://frameworks.dev",
  //   },
  // ],
  // creator: "Frameworks",
  // publisher: "Frameworks",
  
  // // SEO
  // robots: {
  //   index: true,
  //   follow: true,
  // },
  
  // // Social Media
  // openGraph: {
  //   title: "Frameworks",
  //   description: "Frameworks",
  //   url: "https://frameworks.dev",
  //   siteName: "Frameworks",
  //   images: [
  //     {
  //       url: "/og.png",
  //       width: 1200,
  //       height: 630,
  //     },
  //   ],
  //   locale: "en-US",
  //   type: "website",
  // },
  
  // twitter: {
  //   card: "summary_large_image",
  //   title: "Frameworks",
  //   description: "Frameworks",
  //   images: "/og.png",
  //   creator: "@frameworks",
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
